export declare const VERDICTS: string[];
export declare const HIGH_TRUST: Set<string>;
export declare const MID_TRUST: Set<string>;
export declare const LOW_TRUST_RE: RegExp;
export declare const SHORTENER_RE: RegExp;
export declare const PRETTY: {
    "reuters.com": string;
    "apnews.com": string;
    "ap.org": string;
    "bbc.com": string;
    "bbc.co.uk": string;
    "npr.org": string;
    "pbs.org": string;
    "nytimes.com": string;
    "washingtonpost.com": string;
    "wsj.com": string;
    "bloomberg.com": string;
    "economist.com": string;
    "theguardian.com": string;
    "cnn.com": string;
    "nbcnews.com": string;
    "abcnews.go.com": string;
    "cbsnews.com": string;
    "usatoday.com": string;
    "politico.com": string;
    "axios.com": string;
    "forbes.com": string;
    "time.com": string;
    "theatlantic.com": string;
    "latimes.com": string;
    "britannica.com": string;
    "nature.com": string;
    "science.org": string;
    "scientificamerican.com": string;
    "nationalgeographic.com": string;
    "pewresearch.org": string;
    "snopes.com": string;
    "factcheck.org": string;
    "politifact.com": string;
    "who.int": string;
    "un.org": string;
    "worldbank.org": string;
    "imf.org": string;
    "oecd.org": string;
    "investopedia.com": string;
    "history.com": string;
    "cnbc.com": string;
    "wikipedia.org": string;
    "census.gov": string;
    "bls.gov": string;
    "cdc.gov": string;
    "nasa.gov": string;
    "noaa.gov": string;
    "federalreserve.gov": string;
    "congress.gov": string;
    "usa.gov": string;
    "cftc.gov": string;
    "sec.gov": string;
    "bea.gov": string;
    "bjs.ojp.gov": string;
    "fbi.gov": string;
    "archives.gov": string;
    "loc.gov": string;
    "ssa.gov": string;
    "cbo.gov": string;
    "state.gov": string;
    "treasury.gov": string;
    "justice.gov": string;
    "whitehouse.gov": string;
    "nih.gov": string;
    "weather.gov": string;
    "eia.gov": string;
    "supremecourt.gov": string;
    "stlouisfed.org": string;
    "europa.eu": string;
    "mayoclinic.org": string;
    "webmd.com": string;
    "healthline.com": string;
    "businessinsider.com": string;
    "vox.com": string;
    "thehill.com": string;
    "newsweek.com": string;
    "usnews.com": string;
};
export declare function cleanText(s: any): string;
export declare function truncateOnAir(s: any, n: any): string;
export declare function hostOf(url: any): string | null;
export declare function prettyName(host: any): any;
export declare function trustTier(host: any): 0 | 1 | 2 | 3;
export declare function rankCitations(urls: any): {
    url: any;
    host: string | null;
    tier: number;
}[];
export declare function autoAirEligible(ranked: any): boolean;
/**
 * Apply the full editorial policy to a raw verifier result and produce the on-air card body.
 * @param {import("./interfaces/verifier.js").RawVerification} rv
 * @returns {{verdict: string, correction: string, confidence: number, source: {name: string, url: string|null, tier: number}, citations: string[], autoAirEligible: boolean}}
 */
export declare function finalizeVerification(rv: import("./interfaces/verifier.js").RawVerification): {
    verdict: string;
    correction: string;
    confidence: number;
    source: {
        name: string;
        url: string | null;
        tier: number;
    };
    citations: string[];
    autoAirEligible: boolean;
};
